name: Check Oppo Find N6 Orange

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-slim
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Make script executable
        run: chmod +x ./check-oppo-orange.sh

      - name: Run availability check
        run: ./check-oppo-orange.sh
